name: "Symfony 4"
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.0", "8.1", "8.2", "8.3" ]
                symfony: [ "4.0", "5.0", "6.0", "7.0" ]
                exclude:
                    - symfony: 6.0
                      php: 8.0

                    - symfony: 7.0
                      php: 8.0

                    - symfony: 7.0
                      php: 8.1

        name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer require symfony/finder:^${{ matrix.symfony }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit --colors=always
